KaotoIO/kaoto-backend

.github/workflows/analysis.yml, README.md, codecov.yml
Adding codecov.io as another way of meassuring quality of the code.
=> Adding codecov

.github/workflows/generate-docker-image.yml
=> job: Use the  docker action to build

kamelet-support/src/main/java/io/kaoto/backend/metadata/parser/step/kamelet/KameletFileProcessor.java, kamelet-support/src/test/java/io/kaoto/backend/metadata/parser/step/kamelet/KameletParseCatalogTest.java, model/src/main/java/io/kaoto/backend/model/step/Step.java
=> Add required properties to steps

api/src/main/java/io/kaoto/backend/api/resource/StepResource.java, api/src/test/java/io/kaoto/backend/api/resource/StepResourceTest.java
=> Mini catalog endpoint (adding new parameters)

model/pom.xml, model/src/main/java/io/kaoto/backend/model/parameter/Parameter.java, model/src/main/java/io/kaoto/backend/model/parameter/ParameterDeserializer.java
=> bug fix(polymorphism): Adding a workaround for the Parameter

api/src/main/java/io/kaoto/backend/api/resource/IntegrationResource.java, api/src/test/java/io/kaoto/backend/api/resource/IntegrationResourceTest.java, cluster/src/main/java/io/kaoto/backend/deployment/ClusterService.java, cluster/src/test/java/io/kaoto/backend/deployment/ClusterServiceTest.java
Hello, this is a first iteration implementation, I'm interested in the streaming part too, I was thinking about SSE but I can't find much documentation on quarkus and sse, I think that it is possible (and probably simpler) with a websocket.
=> feature(log): Create endpoint to stream log of integration

api/src/main/java/io/kaoto/backend/api/resource/v0/IntegrationResource.java, api/src/main/java/io/kaoto/backend/api/resource/v0/LanguageResource.java, api/src/main/java/io/kaoto/backend/api/resource/v0/StepResource.java, api/src/main/java/io/kaoto/backend/api/resource/v0/ViewDefinitionResource.java, api/src/main/java/io/kaoto/backend/api/resource/v0/request/DeploymentResourceYamlRequest.java, api/src/main/java/io/kaoto/backend/api/resource/v0/response/ViewDefinitionResourceResponse.java, api/src/main/java/io/kaoto/backend/api/resource/v1/DeploymentsResource.java, api/src/main/java/io/kaoto/backend/api/resource/v1/StepResource.java, api/src/main/java/io/kaoto/backend/api/resource/v1/ViewDefinitionResource.java, api/src/main/java/io/kaoto/backend/api/service/language/LanguageService.java, api/src/main/java/io/kaoto/backend/api/service/viewdefinition/parser/GenericViewDefinitionParserService.java, api/src/test/java/io/kaoto/backend/api/resource/v1/DeploymentsResourceTest.java, api/src/test/java/io/kaoto/backend/api/service/deployment/DeploymentServiceTest.java, cluster/src/main/java/io/kaoto/backend/deployment/ClusterService.java, cluster/src/test/java/io/kaoto/backend/deployment/ClusterServiceTest.java, kamelet-support/src/main/java/io/kaoto/backend/KamelPopulator.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/kamelet/KameletBindingDeploymentGeneratorService.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/kamelet/KameletDeploymentGeneratorService.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/step/parser/kamelet/KameletBindingStepParserService.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/step/parser/kamelet/KameletStepParserService.java, kamelet-support/src/test/java/io/kaoto/backend/api/service/step/parser/kamelet/KameletBindingStepParserServiceTest.java, kamelet-support/src/test/java/io/kaoto/backend/api/service/step/parser/kamelet/KameletStepParserServiceTest.java, services-interfaces/src/main/java/io/kaoto/backend/api/service/deployment/generator/DeploymentGeneratorService.java, services-interfaces/src/main/java/io/kaoto/backend/api/service/step/parser/StepParserService.java
=> Deployment: Support all CRDs supported by DSLs.

api/src/main/resources/application.yaml, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/KameletBindingSpec.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/KameletBindingStatus.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/KameletBindingStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/KameletBindingStepRef.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/FlowStepDeserializer.java
Ignore properties we don't understand.
=> Be loosely compatible with other Kamelet  versions

api/src/main/resources/application.yaml, api/src/test/java/io/kaoto/backend/api/resource/v1/DeploymentsResourceTest.java, api/src/test/resources/application.yaml, catalog/src/main/java/io/kaoto/backend/api/metadata/catalog/StepCatalog.java, catalog/src/main/java/io/kaoto/backend/api/metadata/catalog/ViewDefinitionCatalog.java, kamelet-support/src/test/resources/application.yaml, metadata/src/main/java/io/kaoto/backend/metadata/parser/ClusterParseCatalog.java, metadata/src/main/java/io/kaoto/backend/metadata/parser/GitParseCatalog.java, metadata/src/main/java/io/kaoto/backend/metadata/parser/JarParseCatalog.java, metadata/src/main/java/io/kaoto/backend/metadata/parser/LocalFolderParseCatalog.java, model/src/main/java/io/kaoto/backend/model/configuration/Repository.java
To allow backup catalog if cluster is not available
=> !! Add a new change to application.yaml [cluster not available - kamelets]

cluster/src/main/java/io/kaoto/backend/deployment/ClusterService.java, cluster/src/test/java/io/kaoto/backend/deployment/ClusterServiceTest.java, model/src/main/java/io/kaoto/backend/model/deployment/Integration.java
=> feature(api): Enrich deployments endpoint with more data

api/src/main/java/io/kaoto/backend/api/resource/v1/IntegrationsResource.java, api/src/test/java/io/kaoto/backend/api/resource/v1/IntegrationsResourceTest.java
=> feature(api): Return full list of dsl if no dsl found

.github/workflows/generate-docker-image.yml, api/pom.xml, api/src/main/resources/application.yaml, api/src/test/java/io/kaoto/backend/api/service/language/LanguageServiceTest.java, api/src/test/resources/application.properties, camel-route-support/pom.xml, camel-route-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/camelroute/IntegrationDeploymentGeneratorService.java, camel-route-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/camelroute/IntegrationRepresenter.java, camel-route-support/src/main/java/io/kaoto/backend/api/service/step/parser/camelroute/IntegrationStepParserService.java, camel-route-support/src/main/java/io/kaoto/backend/model/deployment/camelroute/Integration.java, camel-route-support/src/main/java/io/kaoto/backend/model/deployment/camelroute/IntegrationSpec.java, camel-route-support/src/test/java/io/kaoto/backend/api/service/deployment/generator/camelroute/IntegrationDeploymentGeneratorServiceTest.java, camel-route-support/src/test/resources/application.properties, camel-route-support/src/test/resources/application.yaml, cluster/pom.xml, cluster/src/test/resources/application.properties, kamelet-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/kamelet/KameletRepresenter.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/step/parser/kamelet/KameletStepParserService.java, kamelet-support/src/test/resources/application.properties, metadata/src/test/resources/application.properties, pom.xml
Now we have a third DSL that generates `kind: Integration` custom resources.
=> feature(camel-routes): Adding new DSL Integration Kind

metadata/src/test/java/io/kaoto/backend/metadata/parser/view/ViewDefinitionDefinitionParseCatalogTest.java
=> fix(test): If we are using a non static branch, we need to be more

cluster/src/main/java/io/kaoto/backend/deployment/ClusterService.java
failed depending on the order of deployment providers
=> bug(cluster): client was throwing an uncaught exception, so deployments

.github/workflows/generate-docker-image.yml, api/src/main/docker/Dockerfile.native
We had to go back to jvm version, let's try to get native image back again.
=> Getting the native docker image back

kamelet-support/src/main/java/io/kaoto/backend/KamelPopulator.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/kamelet/KameletRepresenter.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/step/parser/kamelet/KameletStepParserService.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/FlowStepDeserializer.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/TransformFlowStep.java, kamelet-support/src/test/resources/io/kaoto/backend/api/service/step/parser/kamelet/eip.kamelet.yaml
Adding transform EIP (#130)
Expecting this to work once the following is merged
https://github.com/KaotoIO/camel-component-metadata/pull/3
=> feature(eip): Add transform EIP

kamelet-support/src/main/java/io/kaoto/backend/KamelPopulator.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/kamelet/KameletRepresenter.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/step/parser/kamelet/KameletStepParserService.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/Filter.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/FilterFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/FlowStepDeserializer.java, kamelet-support/src/test/resources/io/kaoto/backend/api/service/step/parser/kamelet/eip.kamelet.yaml
Adding filter EIP (https://github.com/KaotoIO/kaoto-backend/issues/130)
need https://github.com/KaotoIO/camel-component-metadata/pull/4
=> feature(eip): Add filter EIP

.github/workflows/mutations.yml
We are only interested in the last one.
=> feature(mutation): we don't need to run more than one mutation at a time

kamelet-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/kamelet/KameletRepresenter.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/Expression.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/FlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/ChoiceFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/FilterFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/FlowStepDeserializer.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/From.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/SetBodyFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/SetHeaderFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/SetPropertyFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/ToFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/TransformFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/UriFlowStep.java
Before we end up with a God Class and spaguetti code, simplify how new EIP are added and delegate the responsability of each EIP specific features on its class.
=> Eip refactor

kamelet-support/src/main/java/io/kaoto/backend/api/service/step/parser/kamelet/KameletStepParserService.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/Expression.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/FlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/ChoiceFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/FilterFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/RemoveHeaderFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/SetBodyFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/SetHeaderFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/SetPropertyFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/ToFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/TransformFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/UriFlowStep.java
More refactoring to remove duplicated code and make EIP implementations with more sense.
=> refactor(eip): Delegating parsing to each step class

.github/workflows/analysis.yml
=> feature(job): Use pull_request_target to get the sonar cloud token on

api/src/main/docker/Dockerfile.native
This could potentially be reduced even more, but let's start with this.
=> feature(mem): Limit the memory usage on the docker image.

api/src/main/java/io/kaoto/backend/api/resource/v1/StepResource.java, api/src/test/java/io/kaoto/backend/api/resource/v1/StepResourceTest.java
=> Improve steps performance

api/src/main/java/io/kaoto/backend/api/resource/v1/IntegrationsResource.java, api/src/main/java/io/kaoto/backend/api/service/deployment/DeploymentService.java, api/src/test/java/io/kaoto/backend/api/resource/v1/IntegrationsResourceTest.java, api/src/test/resources/io/kaoto/backend/api/resource/eip.kamelet.yaml, kamelet-support/src/main/java/io/kaoto/backend/KamelPopulator.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/step/parser/kamelet/KameletStepParserService.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/ChoiceFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/FilterFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/MarshalFlowStep.java, model/src/main/java/io/kaoto/backend/model/parameter/ArrayParameter.java, model/src/main/java/io/kaoto/backend/model/step/Branch.java
Marshal EIP is right now failing. This is an iteration towards the solution.
=> Some fixes for branches

api/src/test/java/io/kaoto/backend/api/service/deployment/DeploymentServiceTest.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/kamelet/KameletBindingDeploymentGeneratorService.java, kamelet-support/src/test/java/io/kaoto/backend/api/service/deployment/generator/kamelet/KameletBindingDeploymentGeneratorServiceTest.java
=> Disable camel-component support in KameletBinding

.github/workflows/generate-docker-image.yml
If MacOS job passes... we are good to go!
=> feature(docker): Adding MacOS builds

metadata/pom.xml
=> feature(deps): Updating jgit dependency to latest

api/src/main/java/io/kaoto/backend/api/resource/v1/DeploymentsResource.java, camel-route-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/camelroute/IntegrationDeploymentGeneratorService.java, camel-route-support/src/test/java/io/kaoto/backend/api/service/deployment/generator/camelroute/DeploymentGeneratorServiceTest.java, cluster/src/main/java/io/kaoto/backend/deployment/ClusterService.java, cluster/src/test/java/io/kaoto/backend/deployment/ClusterServiceTest.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/kamelet/KameletBindingDeploymentGeneratorService.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/kamelet/KameletDeploymentGeneratorService.java, model/src/main/java/io/kaoto/backend/model/deployment/Deployment.java, services-interfaces/src/main/java/io/kaoto/backend/api/service/deployment/generator/DeploymentGeneratorService.java
Delegate searching of resources to each DSL and make sure no duplicated resources appear on the deployments list.
=> Better cluster management

api/src/main/java/io/kaoto/backend/api/resource/v1/DeploymentsResource.java, cluster/src/main/java/io/kaoto/backend/deployment/ClusterService.java, cluster/src/test/java/io/kaoto/backend/deployment/ClusterServiceTest.java
=> Adds better kind resource management.

api/src/test/resources/io/kaoto/backend/api/resource/eip.kamelet.yaml, kamelet-support/src/main/java/io/kaoto/backend/KamelPopulator.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/kamelet/KameletRepresenter.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/step/parser/kamelet/KameletStepParserService.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/Expression.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/Aggregate.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/AggregateFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/ChoiceFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/FlowStepDeserializer.java, kamelet-support/src/test/resources/io/kaoto/backend/api/service/step/parser/kamelet/eip.kamelet.yaml
=> feature(eip-aggregate): Adding EIP aggregator

api/src/test/resources/io/kaoto/backend/api/resource/eip.kamelet.yaml, kamelet-support/src/main/java/io/kaoto/backend/KamelPopulator.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/kamelet/KameletRepresenter.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/CircuitBreaker.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/CircuitBreakerFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/CircuitBreakerOnFallback.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/FlowStepDeserializer.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/SetHeaderFlowStep.java, kamelet-support/src/test/resources/io/kaoto/backend/api/service/step/parser/kamelet/eip.kamelet.yaml
=> feature(eip): Add circuit-breaker EIP

api/src/test/resources/io/kaoto/backend/api/resource/eip.kamelet.yaml, kamelet-support/src/main/java/io/kaoto/backend/KamelPopulator.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/kamelet/KameletRepresenter.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/Expression.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/Aggregate.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/AggregateFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/CircuitBreaker.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/CircuitBreakerFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/ClaimCheck.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/ClaimCheckFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/ConvertBodyTo.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/ConvertBodyToFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/Delay.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/DelayFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/EIPStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/FlowStepDeserializer.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/LogFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/LogStep.java, kamelet-support/src/test/resources/io/kaoto/backend/api/service/step/parser/kamelet/eip.kamelet.yaml
=> feature(eip): Add delay eip

api/src/test/resources/io/kaoto/backend/api/resource/eip.kamelet.yaml, kamelet-support/src/main/java/io/kaoto/backend/KamelPopulator.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/kamelet/KameletRepresenter.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/DynamicRouter.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/DynamicRouterFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/FlowStepDeserializer.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/UriFlowStep.java, kamelet-support/src/test/resources/io/kaoto/backend/api/service/step/parser/kamelet/eip.kamelet.yaml, metadata/src/main/java/io/kaoto/backend/metadata/catalog/CatalogCollection.java, metadata/src/main/java/io/kaoto/backend/metadata/catalog/InMemoryCatalog.java
=> feature(eip): Add Dynamic Route EIP

kamelet-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/kamelet/KameletRepresenter.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/Expression.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/CircuitBreaker.java
=> codesmells: Replace strings with constants and avoid duplicated name

api/src/test/resources/io/kaoto/backend/api/resource/eip.kamelet.yaml, kamelet-support/src/main/java/io/kaoto/backend/KamelPopulator.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/kamelet/KameletRepresenter.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/Enrich.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/EnrichFlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/FlowStepDeserializer.java, kamelet-support/src/test/resources/io/kaoto/backend/api/service/step/parser/kamelet/eip.kamelet.yaml
=> feature(eip): Add Enrich EIP

api/src/main/java/io/kaoto/backend/api/resource/v1/IntegrationsResource.java, api/src/test/resources/io/kaoto/backend/api/resource/eip.kamelet.yaml, kamelet-support/src/main/java/io/kaoto/backend/KamelPopulator.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/deployment/generator/kamelet/KameletRepresenter.java, kamelet-support/src/main/java/io/kaoto/backend/api/service/step/parser/kamelet/KameletStepParserService.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/Expression.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/FlowStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/Aggregate.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/CircuitBreaker.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/ClaimCheck.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/ConvertBodyTo.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/Delay.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/DynamicRouter.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/EIPStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/Enrich.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/FlowStepDeserializer.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/LogStep.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/Loop.java, kamelet-support/src/main/java/io/kaoto/backend/model/deployment/kamelet/step/LoopFlowStep.java, kamelet-support/src/test/java/io/kaoto/backend/api/service/step/parser/kamelet/KameletStepParserServiceTest.java, kamelet-support/src/test/resources/io/kaoto/backend/api/service/step/parser/kamelet/eip.kamelet.yaml
=> feature: Add new EIP Loop + refactoring for Expressions

api/src/main/resources/application.yaml, camel-route-support/src/test/resources/application.yaml, catalog/src/main/java/io/kaoto/backend/api/metadata/catalog/StepCatalog.java, catalog/src/main/java/io/kaoto/backend/api/metadata/catalog/StepCatalogParser.java, kamelet-support/src/main/java/io/kaoto/backend/metadata/parser/step/camelroute/CamelRouteParseCatalog.java, kamelet-support/src/main/java/io/kaoto/backend/metadata/parser/step/kamelet/KameletParseCatalog.java, model/src/main/java/io/kaoto/backend/model/configuration/Repository.java
Reducing startup time (we only parse with the proper parsers)
=> feature(repositories): Add filter to md repositories
